//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedParts.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsedParts.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add image from saved.
        /// </summary>
        public static string AddImageFromSaved {
            get {
                return ResourceManager.GetString("AddImageFromSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add image using camera.
        /// </summary>
        public static string AddImageUsingCamera {
            get {
                return ResourceManager.GetString("AddImageUsingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorites.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllManufacturers {
            get {
                return ResourceManager.GetString("AllManufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all orders.
        /// </summary>
        public static string AllOrdersTitle {
            get {
                return ResourceManager.GetString("AllOrdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any.
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO.BUZAP.BY.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string CarsCount {
            get {
                return ResourceManager.GetString("CarsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days.
        /// </summary>
        public static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        public static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -choose-.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string FavOrdersTitle {
            get {
                return ResourceManager.GetString("FavOrdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total: {0}, manufacturer: {1}.
        /// </summary>
        public static string FilterAndTotalFormat {
            get {
                return ResourceManager.GetString("FilterAndTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 days.
        /// </summary>
        public static string From1To3 {
            get {
                return ResourceManager.GetString("From1To3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-7 days.
        /// </summary>
        public static string From4To7 {
            get {
                return ResourceManager.GetString("From4To7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send error report?.
        /// </summary>
        public static string Generic_DoYouWantToSendErrorReport {
            get {
                return ResourceManager.GetString("Generic_DoYouWantToSendErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string Generic_ServerBusinessErrorTitle {
            get {
                return ResourceManager.GetString("Generic_ServerBusinessErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string Generic_UnknownError {
            get {
                return ResourceManager.GetString("Generic_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string Generic_UnknownServerErrorBody {
            get {
                return ResourceManager.GetString("Generic_UnknownServerErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Generic_UnknownServerErrorTitle {
            get {
                return ResourceManager.GetString("Generic_UnknownServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try to check your internet connection.
        /// </summary>
        public static string Generic_WebError {
            get {
                return ResourceManager.GetString("Generic_WebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make offer.
        /// </summary>
        public static string MakeOffer {
            get {
                return ResourceManager.GetString("MakeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make offer.
        /// </summary>
        public static string MakeOfferTitle {
            get {
                return ResourceManager.GetString("MakeOfferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manufacturers.
        /// </summary>
        public static string ManufacturersTitle {
            get {
                return ResourceManager.GetString("ManufacturersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mint.
        /// </summary>
        public static string Mint {
            get {
                return ResourceManager.GetString("Mint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7+ days.
        /// </summary>
        public static string MoreThan7 {
            get {
                return ResourceManager.GetString("MoreThan7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my orders.
        /// </summary>
        public static string MyOrdersTitle {
            get {
                return ResourceManager.GetString("MyOrdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in.
        /// </summary>
        public static string NeedAuthorization {
            get {
                return ResourceManager.GetString("NeedAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paid.
        /// </summary>
        public static string NonFree {
            get {
                return ResourceManager.GetString("NonFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoOffers {
            get {
                return ResourceManager.GetString("NoOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoOrders {
            get {
                return ResourceManager.GetString("NoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New order notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string OffersCount {
            get {
                return ResourceManager.GetString("OffersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offers.
        /// </summary>
        public static string OffersTitle {
            get {
                return ResourceManager.GetString("OffersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOO.
        /// </summary>
        public static string Ooo {
            get {
                return ResourceManager.GetString("Ooo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string OrderDetailsTitle {
            get {
                return ResourceManager.GetString("OrderDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders.
        /// </summary>
        public static string OrdersTitle {
            get {
                return ResourceManager.GetString("OrdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Type.
        /// </summary>
        public static string OrganizationType {
            get {
                return ResourceManager.GetString("OrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is only for authorized users. 
        ///Please log in using your credentials or create a new account..
        /// </summary>
        public static string PleaseLoginOrRegister {
            get {
                return ResourceManager.GetString("PleaseLoginOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to possible.
        /// </summary>
        public static string Possible {
            get {
                return ResourceManager.GetString("Possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (USD).
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration.
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove from favorites.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove image.
        /// </summary>
        public static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very bad.
        /// </summary>
        public static string VeryBad {
            get {
                return ResourceManager.GetString("VeryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty.
        /// </summary>
        public static string Warranty {
            get {
                return ResourceManager.GetString("Warranty", resourceCulture);
            }
        }
    }
}
